#options(unzip = 'internal')
#.libPaths(c('/opt/conda/lib/R/library'))

install.packages("devtools")
install.packages("plyr")
install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("forecast")
install.packages("rsqlite")
install.packages("reshape2")
install.packages("rcurl")
install.packages("crayon")
install.packages("htmltools")
install.packages("htmlwidgets")
install.packages("xml")
install.packages("data.table")
install.packages("httr")
install.packages("rlist")
install.packages("roxygen2")
install.packages("ggplot2")
install.packages("hexbin")
install.packages("htmlTable")
#install('dbGaP2x')

library(devtools)
library(parallel)
library(htmlTable)
